[project]
name = "rl-ad"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "gymnasium[other]>=1.2.2",
    "highway-env>=1.10.2",
    "matplotlib>=3.10.7",
    "numpy>=2.3.4",
]
